import { auth, onAuthStateChanged, signOut, collection, getDocs, query, orderBy, limit, doc, getDoc, updateDoc, serverTimestamp, runTransaction } from "./firebase.js";
import { adminLogin } from "./auth/adminAuth.js";
import { requireRole, can } from "./utils/security.js";
import { listCollection, saveEntity, removeEntity, getOne } from "./services/courseService.js";
import { saveLecture } from "./services/lectureService.js";
import { createRegistrationRequest, listStudents, updateStudent, createStudent } from "./services/studentService.js";
import { listAssistants, createAssistant, updateAssistant } from "./services/assistantService.js";
import { listImages, uploadImage, deleteImage } from "./services/imageService.js";
import { listPosts, createInstructorReply, setOfficialReply, deletePost } from "./services/discussionService.js";
import { $, $$, toast, setBusy, esc, formatDate, confirmDialog, modal, normalizeCode } from "./utils/helpers.js";

let profile=null;
const PERMISSIONS=["students","classes","subjects","courses","lectures","books","exams","results","discussions","images"];
const labels={registrationRequests:"طلبات التسجيل",students:"الطلاب",classes:"الصفوف",subjects:"المواد",courses:"الكورسات",lectures:"المحاضرات",books:"الكتب",exams:"الامتحانات",discussions:"المناقشات",assistants:"المشرفون المساعدون"};

async function init(){
  profile=await requireRole(["super_admin","assistant"]); $("#admin-name").textContent=profile.displayName||profile.email||"المشرف";
  if(profile.role!=="super_admin") $$(".super-only").forEach(x=>x.hidden=true);
  await loadStats(); bindNav(); loadSection("registrationRequests");
}
async function loadStats(){for(const n of ["students","registrationRequests","classes","subjects","courses","lectures","books","exams","discussionReports"]){try{const s=await getDocs(query(collection(db,n),limit(1)));const el=$(`[data-stat="${n}"]`);if(el)el.textContent=s.size?"1+":"0";}catch{}}}
function bindNav(){$$(".nav-btn").forEach(b=>b.onclick=()=>loadSection(b.dataset.section));}
async function loadSection(section){
  try{
    if(section==="registrationRequests")return can(profile,"students")?renderRequests():toast("لا تملك صلاحية","error");
    if(section==="students")return can(profile,"students")?renderStudents():toast("لا تملك صلاحية","error");
    if(["classes","subjects","courses","books","exams"].includes(section))return can(profile,section)?renderCrud(section):toast("لا تملك صلاحية","error");
    if(section==="questions")return can(profile,"exams")?renderQuestions():toast("لا تملك صلاحية","error");
    if(section==="images")return can(profile,"images")?renderImages():toast("لا تملك صلاحية","error");
    if(section==="lectures")return can(profile,"lectures")?renderLectures():toast("لا تملك صلاحية","error");
    if(section==="discussions")return can(profile,"discussions")?renderDiscussions():toast("لا تملك صلاحية","error");
    if(section==="assistants")return profile.role==="super_admin"?renderAssistants():toast("للمشرف الأساسي فقط","error");
  }catch(e){toast(e.message||"حدث خطأ","error")}
}
async function renderRequests(){
 const xs=await listCollection("registrationRequests",{limitN:100});
 $("#admin-content").innerHTML=`<div class="section-head"><div><h2>طلبات التسجيل</h2><p>الطلبات القادمة من نموذج الطالب تكون مكتملة ولا تُقبل البيانات الناقصة.</p></div></div><div class="table-wrap"><table><thead><tr><th>الاسم</th><th>الهاتف</th><th>الصف</th><th>الحالة</th><th>الإجراء</th></tr></thead><tbody>${xs.map(x=>`<tr><td>${esc(x.name)}</td><td>${esc(x.phone)}</td><td>${esc(x.className)}</td><td>${esc(x.status)}</td><td>${x.status==="pending"?`<button class="btn small" data-approve="${x.id}">اعتماد</button> <button class="btn small danger" data-reject="${x.id}">رفض</button>`:"—"}</td></tr>`).join("")||`<tr><td colspan="5">لا توجد طلبات حاليًا.</td></tr>`}</tbody></table></div>`;
 $$("[data-approve]").forEach(b=>b.onclick=()=>approveRequest(b.dataset.approve)); $$("[data-reject]").forEach(b=>b.onclick=()=>rejectRequest(b.dataset.reject));
}
async function approveRequest(id){
 const s=await getDoc(doc(db,"registrationRequests",id));if(!s.exists())return;const x=s.data();const code=`MANS-${crypto.randomUUID().replace(/-/g,"").slice(0,6).toUpperCase()}`;
 await runTransaction(db,async tx=>{const req=await tx.get(doc(db,"registrationRequests",id));if(req.data()?.status!=="pending")throw new Error("الطلب تمت معالجته بالفعل.");const st=doc(collection(db,"students"));const key=doc(db,"uniqueKeys",`code_${code}`);tx.set(st,{name:x.name,phone:x.phone,phoneNormalized:x.phoneNormalized,classId:x.classId,className:x.className,loginCode:code,status:"active",requestId:id,createdAt:serverTimestamp(),approvedAt:serverTimestamp(),updatedAt:serverTimestamp()});tx.set(key,{type:"loginCode",studentId:st.id,createdAt:serverTimestamp()});tx.update(doc(db,"registrationRequests",id),{status:"approved",approvedAt:serverTimestamp(),approvedBy:auth.currentUser.uid});tx.set(doc(db,"phoneLocks",x.phoneNormalized.replace(/\W/g,"")),{status:"approved",studentId:st.id,createdAt:serverTimestamp()});});
 toast(`تم الاعتماد. كود الطالب: ${code}`,"success");renderRequests();
}
async function rejectRequest(id){if(!(await confirmDialog("رفض هذا الطلب؟ سيتم تحرير رقم الهاتف ليتمكن صاحبه من إعادة التقديم.")))return;const s=await getDoc(doc(db,"registrationRequests",id));if(!s.exists())return;await runTransaction(db,async tx=>{const r=await tx.get(doc(db,"registrationRequests",id));if(r.data()?.status!=="pending")throw new Error("الطلب تمت معالجته بالفعل.");tx.update(doc(db,"registrationRequests",id),{status:"rejected",rejectedAt:serverTimestamp(),rejectedBy:auth.currentUser.uid});tx.delete(doc(db,"phoneLocks",String(r.data()?.phoneNormalized||"").replace(/\W/g,"")));});toast("تم رفض الطلب","success");renderRequests()}

async function renderStudents(){const xs=await listStudents({});$("#admin-content").innerHTML=`<div class="section-head"><div><h2>الطلاب</h2><p>يمكن للمشرف إضافة طالب ببيانات ناقصة. عند أول دخول سيُطلب من الطالب استكمال الناقص.</p></div><button class="btn primary" id="add-student">إضافة طالب</button></div><div class="table-wrap"><table><thead><tr><th>الاسم</th><th>الهاتف</th><th>الصف</th><th>الكود</th><th>الحالة</th><th></th></tr></thead><tbody>${xs.map(x=>`<tr><td>${esc(x.name||"—")}</td><td>${esc(x.phone||"—")}</td><td>${esc(x.className||"—")}</td><td><code>${esc(x.loginCode)}</code></td><td>${esc(x.status)}</td><td><button class="btn small" data-edit-student="${x.id}">تعديل</button></td></tr>`).join("")||`<tr><td colspan="6">لا توجد بيانات حاليًا.</td></tr>`}</tbody></table></div>`;$("#add-student").onclick=()=>studentModal();$$("[data-edit-student]").forEach(b=>b.onclick=()=>studentModal(b.dataset.editStudent));}
async function studentModal(id){
 const x=id?await getOne("students",id):{};const classes=await listCollection("classes",{field:"status",value:"active",limitN:200});
 const m=modal(id?"تعديل طالب":"إضافة طالب",`<form id="student-form" class="form-grid"><label>الاسم الكامل<input name="name" value="${esc(x.name||"")}"></label><label>رقم الهاتف<input name="phone" inputmode="tel" value="${esc(x.phone||"")}></label><label>الصف<select name="classId"><option value="">${id?"بدون صف — يُستكمل لاحقًا":"اختر الصف أو اتركه ناقصًا"}</option>${classes.map(c=>`<option value="${c.id}" ${x.classId===c.id?"selected":""}>${esc(c.name)}</option>`).join("")}</select></label>${!id?`<label>كود الدخول<input name="loginCode" placeholder="MANS-7K29QX" required></label>`:`<label>الحالة<select name="status"><option value="active" ${x.status==="active"?"selected":""}>active</option><option value="suspended" ${x.status==="suspended"?"selected":""}>suspended</option><option value="disabled" ${x.status==="disabled"?"selected":""}>disabled</option></select></label>`}<button class="btn primary">حفظ</button></form>`);
 $("#student-form",m).onsubmit=async e=>{e.preventDefault();setBusy(e.submitter,true);try{const f=Object.fromEntries(new FormData(e.target));const cls=classes.find(c=>c.id===f.classId);if(id){await updateStudent(id,{name:f.name,phone:f.phone,classId:f.classId,className:cls?.name||"",status:f.status});}else{await createStudent({name:f.name,phone:f.phone,classId:f.classId,className:cls?.name||"",loginCode:normalizeCode(f.loginCode)});}m.remove();toast("تم حفظ الطالب","success");renderStudents()}catch(err){toast(err.message,"error")}finally{setBusy(e.submitter,false)}};
}

async function renderCrud(name){const xs=await listCollection(name,{limitN:100});const label=labels[name];$("#admin-content").innerHTML=`<div class="section-head"><h2>${label}</h2><button class="btn primary" id="add-item">إضافة</button></div><div class="grid">${xs.map(x=>`<article class="card"><h3>${esc(x.name||x.title)}</h3><p>${esc(x.description||"")}</p><small>${esc(x.status||"")}</small><div class="actions"><button class="btn small" data-edit="${x.id}">تعديل</button> <button class="btn small danger" data-delete="${x.id}">حذف</button></div></article>`).join("")||`<div class="empty">لا توجد بيانات حاليًا.</div>`}</div>`;$("#add-item").onclick=()=>crudModal(name);$$("[data-edit]").forEach(b=>b.onclick=()=>crudModal(name,b.dataset.edit));$$("[data-delete]").forEach(b=>b.onclick=async()=>{if(await confirmDialog("هل أنت متأكد من الحذف؟")){await removeEntity(name,b.dataset.delete);renderCrud(name)}})}
async function crudModal(name,id){
 const x=id?(await getOne(name,id))||{}:{};let fields=`<label>الاسم/العنوان<input name="name" value="${esc(x.name||x.title||"")}" required></label><label>الوصف<textarea name="description">${esc(x.description||"")}</textarea></label>`;
 if(["subjects","courses"].includes(name)){const classes=await listCollection("classes",{field:"status",value:"active",limitN:200});fields+=`<label>الصف<select name="classId"><option value="">اختر</option>${classes.map(c=>`<option value="${c.id}" ${x.classId===c.id?"selected":""}>${esc(c.name)}</option>`).join("")}</select></label>`}
 if(name==="courses"){const subjects=await listCollection("subjects",{limitN:200});fields+=`<label>المادة<select name="subjectId"><option value="">اختر</option>${subjects.map(s=>`<option value="${s.id}" ${x.subjectId===s.id?"selected":""}>${esc(s.name)}</option>`).join("")}</select></label><label>اسم المدرس<input name="teacherName" value="${esc(x.teacherName||"")}"></label>`}
 if(name==="books")fields+=`<label>رابط Google Drive<input name="driveUrl" value="${esc(x.driveUrl||"")}" required></label><label>Course ID<input name="courseId" value="${esc(x.courseId||"")}" required></label><label>Lecture ID اختياري<input name="lectureId" value="${esc(x.lectureId||"")}"></label><label>النوع<input name="type" value="${esc(x.type||"pdf")}"></label>`;
 if(name==="exams")fields+=`<label>Course ID<input name="courseId" value="${esc(x.courseId||"")}" required></label><label>Lecture ID اختياري<input name="lectureId" value="${esc(x.lectureId||"")}"></label><label>المدة بالدقائق<input type="number" min="1" name="duration" value="${esc(x.duration||30)}"></label><label>الصف ID اختياري<input name="classId" value="${esc(x.classId||"")}"></label>`;
 fields+=`<label>الحالة<select name="status"><option value="active" ${x.status!=="disabled"?"selected":""}>active</option><option value="disabled" ${x.status==="disabled"?"selected":""}>disabled</option></select></label><button class="btn primary">حفظ</button>`;
 const m=modal(id?"تعديل":"إضافة",`<form id="crud-form" class="form-grid">${fields}</form>`);$("#crud-form",m).onsubmit=async e=>{e.preventDefault();try{const f=Object.fromEntries(new FormData(e.target));const data={...f};if(name==="books"||name==="exams"){data.title=data.name;delete data.name}if(name==="exams")data.questionsCount=Number(data.questionsCount||0);await saveEntity(name,id,data);m.remove();toast("تم الحفظ","success");renderCrud(name)}catch(err){toast(err.message,"error")}};
}
async function renderQuestions(){
 const xs=await listCollection("questions",{limitN:100});
 $("#admin-content").innerHTML=`<div class="section-head"><div><h2>أسئلة الامتحانات</h2><p>الإجابة الصحيحة لا تُرسل للطالب؛ يتم استخدامها فقط داخل Cloud Function عند التصحيح.</p></div><button class="btn primary" id="add-question">إضافة سؤال</button></div><div class="grid">${xs.map(x=>`<article class="card"><h3>${esc(x.question)}</h3><p>Exam: ${esc(x.examId)}</p><small>${(x.options||[]).map(esc).join(" | ")}</small><div><button class="btn small" data-edit-question="${x.id}">تعديل</button><button class="btn small danger" data-delete-question="${x.id}">حذف</button></div></article>`).join("")||`<div class="empty">لا توجد أسئلة حاليًا.</div>`}</div>`;
 $("#add-question").onclick=()=>questionModal();$$("[data-edit-question]").forEach(b=>b.onclick=()=>questionModal(b.dataset.editQuestion));$$("[data-delete-question]").forEach(b=>b.onclick=async()=>{if(await confirmDialog("حذف السؤال؟")){await removeEntity("questions",b.dataset.deleteQuestion);renderQuestions()}});
}
async function questionModal(id){
 const x=id?(await getOne("questions",id))||{}:{};const m=modal(id?"تعديل سؤال":"إضافة سؤال",`<form id="question-form" class="form-grid"><label>Exam ID<input name="examId" value="${esc(x.examId||"")}" required></label><label>السؤال<textarea name="question" required>${esc(x.question||"")}</textarea></label><label>الاختيارات <small>اكتب كل اختيار في سطر</small><textarea name="options" required>${esc((x.options||[]).join("\n"))}</textarea></label><label>الإجابة الصحيحة <input name="correctAnswer" value="${esc(x.correctAnswer||"")}" required></label><label>النقاط<input type="number" min="1" name="points" value="${esc(x.points||1)}"></label><label>الترتيب<input type="number" name="sortOrder" value="${esc(x.sortOrder||0)}"></label><button class="btn primary">حفظ</button></form>`);$("#question-form",m).onsubmit=async e=>{e.preventDefault();try{const f=Object.fromEntries(new FormData(e.target));f.options=f.options.split(/\r?\n/).map(v=>v.trim()).filter(Boolean);f.points=Number(f.points||1);f.sortOrder=Number(f.sortOrder||0);await saveEntity("questions",id,f);m.remove();toast("تم حفظ السؤال","success");renderQuestions()}catch(err){toast(err.message,"error")}};
}
async function renderImages(){
 const xs=await listImages();$("#admin-content").innerHTML=`<div class="section-head"><div><h2>إدارة الصور</h2><p>الصور تُرفع عبر ImgBB Proxy فقط، وFirestore يحفظ بيانات وروابط الصورة.</p></div><button class="btn primary" id="upload-image">رفع صورة</button></div><div class="image-grid">${xs.map(x=>`<article class="card image-card"><img src="${esc(x.thumbUrl||x.url)}" loading="lazy" alt="${esc(x.title||"")}"><h3>${esc(x.title||"بدون عنوان")}</h3><small>${esc(x.category||"general")}</small><div class="image-actions"><button class="btn small" data-copy-image="${esc(x.url)}">نسخ الرابط</button><button class="btn small danger" data-delete-image="${x.id}">حذف</button></div></article>`).join("")||`<div class="empty">لا توجد صور حاليًا.</div>`}</div>`;
 $("#upload-image").onclick=()=>imageModal();$$("[data-delete-image]").forEach(b=>b.onclick=async()=>{if(await confirmDialog("حذف الصورة؟")){await deleteImage(b.dataset.deleteImage);renderImages()}});$$("[data-copy-image]").forEach(b=>b.onclick=async()=>{await navigator.clipboard.writeText(b.dataset.copyImage);toast("تم نسخ الرابط","success")});
}
async function imageModal(){const m=modal("رفع صورة",`<form id="image-form" class="form-grid"><label>الصورة<input type="file" name="image" accept="image/jpeg,image/png,image/webp,image/gif" required></label><label>العنوان<input name="title"></label><label>التصنيف<select name="category"><option>general</option><option>classes</option><option>subjects</option><option>courses</option><option>lectures</option><option>books</option><option>exams</option></select></label><button class="btn primary">رفع</button></form>`);$("#image-form",m).onsubmit=async e=>{e.preventDefault();setBusy(e.submitter,true);try{const f=new FormData(e.target);await uploadImage(f.get("image"),{title:f.get("title"),category:f.get("category")});m.remove();toast("تم رفع الصورة","success");renderImages()}catch(err){toast(err.message,"error")}finally{setBusy(e.submitter,false)}}}

async function renderLectures(){const xs=await listCollection("lectures",{limitN:100});$("#admin-content").innerHTML=`<div class="section-head"><h2>المحاضرات</h2><button class="btn primary" id="add-lec">إضافة</button></div><div class="grid">${xs.map(x=>`<article class="card"><h3>${esc(x.title)}</h3><p>${esc(x.description||"")}</p><small>${esc(x.youtubeVideoId||"")}</small><div><button class="btn small" data-edit="${x.id}">تعديل</button></div></article>`).join("")||`<div class="empty">لا توجد محاضرات حاليًا.</div>`}</div>`;$("#add-lec").onclick=()=>lectureModal();$$("[data-edit]").forEach(b=>b.onclick=()=>lectureModal(b.dataset.edit));}
async function lectureModal(id){const x=id?(await getOne("lectures",id))||{}:{};const m=modal("المحاضرة",`<form id="lec-form" class="form-grid"><label>العنوان<input name="title" value="${esc(x.title||"")}" required></label><label>Course ID<input name="courseId" value="${esc(x.courseId||"")}" required></label><label>YouTube URL<input name="youtubeUrl" value="${esc(x.youtubeUrl||"")}" required></label><label>الوصف<textarea name="description">${esc(x.description||"")}</textarea></label><label>الحالة<select name="status"><option value="active">active</option><option value="disabled">disabled</option></select></label><button class="btn primary">حفظ</button></form>`);$("#lec-form",m).onsubmit=async e=>{e.preventDefault();try{await saveLecture(id,Object.fromEntries(new FormData(e.target)));m.remove();toast("تم حفظ المحاضرة","success");renderLectures()}catch(err){toast(err.message,"error")}}}

async function renderDiscussions(){const reports=await listCollection("discussionReports",{limitN:100});$("#admin-content").innerHTML=`<div class="section-head"><div><h2>المناقشات والبلاغات</h2><p>يمكن للمشرف الرد وتثبيت الإجابة الرسمية.</p></div></div><div class="grid">${reports.map(x=>`<article class="card"><h3>بلاغ على ${esc(x.postId)}</h3><p>${esc(x.reason)}</p><small>${formatDate(x.createdAt)}</small><button class="btn small" data-open-post="${x.postId}">فتح المناقشة</button></article>`).join("")||`<div class="empty">لا توجد بلاغات حاليًا.</div>`}</div>`;$$("[data-open-post]").forEach(b=>b.onclick=()=>openDiscussion(b.dataset.openPost));}
async function openDiscussion(postId){const post=await getDoc(doc(db,"discussionPosts",postId));if(!post.exists())return toast("المنشور غير موجود","error");const p=post.data();const posts=await listPosts(p.lectureId);const m=modal("مناقشة المحاضرة",`<div class="discussion-admin">${posts.map(x=>`<article class="post ${x.isInstructorReply?"instructor":""} ${x.isPinned?"pinned":""}"><header><strong>${x.isInstructorReply?"👑 "+esc(x.authorName||"المشرف"):"👤 "+esc(x.authorName||"طالب")}</strong>${x.isPinned?"<span class=badge>إجابة رسمية</span>":""}</header><p>${esc(x.content)}</p>${x.isInstructorReply?`<button class="btn small" data-unpin="${x.id}">${x.isPinned?"إلغاء التثبيت":"تثبيت كإجابة رسمية"}</button>`:""}</article>`).join("")}</div><hr><form id="admin-reply" class="form-grid"><textarea name="content" required maxlength="3000" placeholder="اكتب رد المشرف..."></textarea><label><input type="checkbox" name="official"> اجعل الرد إجابة رسمية مثبتة</label><button class="btn primary">إرسال الرد</button></form>`);$("#admin-reply",m).onsubmit=async e=>{e.preventDefault();try{const f=new FormData(e.target);const created=await createInstructorReply({lectureId:p.lectureId,courseId:p.courseId,content:f.get("content"),parentId:postId,official:false});if(f.get("official")==="on"&&created.id)await setOfficialReply(created.id,true);m.remove();toast("تم نشر رد المشرف","success");openDiscussion(postId)}catch(err){toast(err.message,"error")}};$$("[data-unpin]",m).forEach(b=>b.onclick=async()=>{try{await setOfficialReply(b.dataset.unpin,!b.textContent.includes("إلغاء"));m.remove();openDiscussion(postId)}catch(e){toast(e.message,"error")}})}

async function renderAssistants(){const xs=await listAssistants();$("#admin-content").innerHTML=`<div class="section-head"><h2>المشرفون المساعدون</h2><button class="btn primary" id="add-assistant">إضافة مشرف مساعد</button></div><div class="grid">${xs.map(x=>`<article class="card"><h3>${esc(x.displayName||x.email)}</h3><p>${esc(x.email||"")}</p><p>${Object.entries(x.permissions||{}).filter(([,v])=>v).map(([k])=>esc(k)).join("، ")||"بدون صلاحيات"}</p><small>الحالة: ${esc(x.status||"active")}</small><div><button class="btn small" data-edit-assistant="${x.id}">تعديل</button></div></article>`).join("")||`<div class="empty">لا يوجد مشرفون مساعدون.</div>`}</div>`;$("#add-assistant").onclick=()=>assistantModal();$$("[data-edit-assistant]").forEach(b=>b.onclick=()=>assistantModal(b.dataset.editAssistant));}
async function assistantModal(uid){const x=uid?(await getDoc(doc(db,"users",uid))).data()||{}:{};const checks=PERMISSIONS.map(p=>`<label><input type="checkbox" name="perm_${p}" ${x.permissions?.[p]?"checked":""}> ${p}</label>`).join("");const m=modal(uid?"تعديل مشرف مساعد":"إضافة مشرف مساعد",`<form id="assistant-form" class="form-grid"><label>الاسم<input name="displayName" value="${esc(x.displayName||"")}" required></label>${uid?"":`<label>البريد الإلكتروني<input type="email" name="email" required></label><label>كلمة المرور المؤقتة<input type="password" name="password" minlength="10" required></label>`}<div class="permissions-grid">${checks}</div><label>الحالة<select name="status"><option value="active" ${x.status!=="disabled"?"selected":""}>active</option><option value="disabled" ${x.status==="disabled"?"selected":""}>disabled</option></select></label><button class="btn primary">حفظ</button></form>`);$("#assistant-form",m).onsubmit=async e=>{e.preventDefault();setBusy(e.submitter,true);try{const f=Object.fromEntries(new FormData(e.target));const permissions={};PERMISSIONS.forEach(p=>permissions[p]=f[`perm_${p}`]==="on");if(uid)await updateAssistant(uid,{displayName:f.displayName,permissions,status:f.status});else await createAssistant({displayName:f.displayName,email:f.email,password:f.password,permissions});m.remove();toast("تم حفظ المشرف المساعد","success");renderAssistants()}catch(err){toast(err.message,"error")}finally{setBusy(e.submitter,false)}}}

document.addEventListener("DOMContentLoaded",()=>{
 $("#login-form")?.addEventListener("submit",async e=>{e.preventDefault();setBusy(e.submitter,true);try{await adminLogin(new FormData(e.target).get("email"),new FormData(e.target).get("password"));location.href="dashboard.html"}catch(err){toast(err.message,"error")}finally{setBusy(e.submitter,false)}});
 onAuthStateChanged(auth,u=>{if(u&&location.pathname.endsWith("dashboard.html"))init().catch(e=>{toast(e.message,"error");signOut(auth).then(()=>location.href="index.html")});if(!u&&location.pathname.endsWith("dashboard.html"))location.href="index.html"});
 $("#logout")?.addEventListener("click",()=>signOut(auth).then(()=>location.href="index.html"));
});
