import { auth, onAuthStateChanged, signOut } from "./firebase.js";
import { signInStudentByCode, getStudentByAuth, completeStudentProfile } from "./services/studentService.js";
import { listCollection, getOne } from "./services/courseService.js";
import { listPosts, createPost, updatePost, deletePost, reportPost } from "./services/discussionService.js";
import { APP_CONFIG } from "./config.js";
import { $, $$, toast, setBusy, formatDate, esc, getYouTubeId, youtubeEmbed, modal, confirmDialog } from "./utils/helpers.js";

let studentProfile=null;
function missingFields(s){const out=[];if(!String(s.name||"").trim())out.push("name");if(!String(s.phoneNormalized||s.phone||"").trim())out.push("phone");if(!String(s.classId||"").trim())out.push("classId");return out;}
function fieldLabel(k){return ({name:"الاسم الكامل",phone:"رقم الهاتف",classId:"الصف"}[k]||k)}
async function ensureCompleteProfile(){
  studentProfile=await getStudentByAuth(auth.currentUser.uid); if(!studentProfile)throw new Error("ملف الطالب غير موجود.");
  const missing=missingFields(studentProfile); if(!missing.length)return true;
  const classes=await listCollection("classes",{field:"status",value:"active",limitN:200});
  const m=modal("استكمال بيانات الطالب",`<p>المشرف أنشأ حسابك، لكن بعض البيانات ناقصة. يجب استكمالها مرة واحدة قبل الوصول إلى محتوى المنصة.</p><form id="complete-profile" class="form-grid">${missing.includes("name")?`<label>${fieldLabel("name")}<input name="name" maxlength="120" required></label>`:""}${missing.includes("phone")?`<label>${fieldLabel("phone")}<input name="phone" inputmode="tel" required></label>`:""}${missing.includes("classId")?`<label>${fieldLabel("classId")}<select name="classId" required><option value="">اختر الصف</option>${classes.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join("")}</select></label>`:""}<button class="btn primary">حفظ واستكمال الدخول</button></form>`);
  m.querySelector(".modal-close").remove();
  return new Promise(resolve=>{$("#complete-profile",m).onsubmit=async e=>{e.preventDefault();setBusy(e.submitter,true);try{const f=Object.fromEntries(new FormData(e.target));await completeStudentProfile(f);m.remove();toast("تم استكمال بياناتك بنجاح","success");studentProfile=await getStudentByAuth(auth.currentUser.uid);resolve(true);loadDashboard()}catch(err){toast(err.message,"error")}finally{setBusy(e.submitter,false)}}});
}
async function loadDashboard(){
  if(!(await ensureCompleteProfile()))return; const s=studentProfile; $("#student-name").textContent=s.name||"الطالب";
  const subjects=await listCollection("subjects",{filters:[{field:"classId",value:s.classId},{field:"status",value:"active"}]}); const active=subjects.filter(x=>x.status==="active");
  $("#subjects").innerHTML=active.map(x=>`<article class="card"><h3>${esc(x.name)}</h3><p>${esc(x.description||"")}</p><button class="btn small" data-sub="${x.id}">عرض الكورسات</button></article>`).join("")||`<div class="empty">لا توجد مواد حاليًا.</div>`;
  $$("#subjects [data-sub]").forEach(b=>b.onclick=()=>showCourses(b.dataset.sub,s.classId));
}
async function showCourses(subjectId,classId){const courses=(await listCollection("courses",{filters:[{field:"subjectId",value:subjectId},{field:"status",value:"active"}]})).filter(x=>x.classId===classId&&x.status==="active");$("#content-view").innerHTML=`<h2>الكورسات</h2><div class="grid">${courses.map(x=>`<article class="card"><h3>${esc(x.name)}</h3><p>${esc(x.description||"")}</p><button class="btn primary" data-course="${x.id}">المحاضرات</button></article>`).join("")||`<div class="empty">لا توجد كورسات حاليًا.</div>`}</div>`;$$("#content-view [data-course]").forEach(b=>b.onclick=()=>showLectures(b.dataset.course));}
async function showLectures(courseId){const lectures=(await listCollection("lectures",{filters:[{field:"courseId",value:courseId},{field:"status",value:"active"}]})).filter(x=>x.status==="active");$("#content-view").innerHTML=`<div class="section-head"><h2>المحاضرات</h2><button class="btn ghost" id="back-course">رجوع</button></div><div class="grid">${lectures.map(x=>`<article class="card"><h3>${esc(x.title)}</h3><p>${esc(x.description||"")}</p><button class="btn primary" data-lec="${x.id}">فتح المحاضرة</button></article>`).join("")||`<div class="empty">لا توجد محاضرات حاليًا.</div>`}</div>`;$$("#content-view [data-lec]").forEach(b=>b.onclick=()=>showLecture(b.dataset.lec));}
async function showLecture(lectureId){
 const l=await getOne("lectures",lectureId);if(!l)return toast("المحاضرة غير موجودة","error");const books=(await listCollection("books",{filters:[{field:"lectureId",value:lectureId},{field:"status",value:"active"}]})).filter(x=>x.status==="active");const exams=(await listCollection("exams",{filters:[{field:"lectureId",value:lectureId},{field:"status",value:"active"}]})).filter(x=>x.status==="active");const posts=await listPosts(lectureId);
 $("#content-view").innerHTML=`<section class="lecture-view"><div class="video-wrap"><iframe src="${youtubeEmbed(l.youtubeVideoId||getYouTubeId(l.youtubeUrl))}" allowfullscreen loading="lazy" title="${esc(l.title)}"></iframe></div><h2>${esc(l.title)}</h2><p>${esc(l.description||"")}</p><div class="grid two"><div class="card"><h3>📖 الكتب</h3>${books.map(b=>`<a class="resource" href="${esc(b.driveUrl)}" target="_blank" rel="noopener">${esc(b.title)}</a>`).join("")||"<p>لا توجد كتب حاليًا.</p>"}</div><div class="card"><h3>📝 الامتحانات</h3>${exams.map(e=>`<div class="resource"><span>${esc(e.title)}</span> <button class="btn small" data-exam="${e.id}">ابدأ</button></div>`).join("")||"<p>لا توجد امتحانات حاليًا.</p>"}</div></div><section class="discussion card"><h3>💬 مناقشة المحاضرة</h3><form id="post-form"><textarea name="content" maxlength="3000" required placeholder="اكتب سؤالك أو استفسارك عن هذه المحاضرة..."></textarea><button class="btn primary">نشر السؤال</button></form><div id="posts">${renderPosts(posts)}</div></section></section>`;
 $("#post-form").onsubmit=async e=>{e.preventDefault();try{await createPost({lectureId,courseId:l.courseId,content:new FormData(e.target).get("content")});toast("تم نشر سؤالك","success");showLecture(lectureId)}catch(err){toast(err.message,"error")}};
 $$("#posts [data-reply]").forEach(b=>b.onclick=()=>replyPost(b.dataset.reply,lectureId,l.courseId));$$("#posts [data-edit]").forEach(b=>b.onclick=()=>editPost(b.dataset.edit,lectureId));$$("#posts [data-delete]").forEach(b=>b.onclick=async()=>{if(await confirmDialog("هل أنت متأكد من حذف منشورك؟")){await deletePost(b.dataset.delete);showLecture(lectureId)}});$$("#posts [data-report]").forEach(b=>b.onclick=async()=>{try{await reportPost(b.dataset.report,"محتوى غير مناسب");toast("تم إرسال البلاغ","success")}catch(e){toast(e.message,"error")}});$$("#content-view [data-exam]").forEach(b=>b.onclick=()=>startExam(b.dataset.exam));
}
function renderPosts(posts){const pinned=posts.filter(p=>p.isPinned&&p.isInstructorReply),rest=posts.filter(p=>!(p.isPinned&&p.isInstructorReply));const arr=[...pinned,...rest.filter(p=>p.isInstructorReply),...rest.filter(p=>!p.isInstructorReply)];return arr.map(p=>`<article class="post ${p.isInstructorReply?"instructor":""} ${p.isPinned?"pinned":""}" style="margin-inline-start:${p.parentId?"24px":"0"}"><header><strong>${p.isInstructorReply?"👑 "+esc(p.authorName||"المشرف"):"👤 "+esc(p.authorName||"طالب")}</strong>${p.isInstructorReply?`<span class="badge">${p.isPinned?"الإجابة الرسمية":"رد المشرف"}</span>`:""}<time>${formatDate(p.createdAt)}</time></header><p>${esc(p.content)}</p><footer><button data-reply="${p.id}" class="link">رد</button>${p.studentId===auth.currentUser.uid?`<button data-edit="${p.id}" class="link">تعديل</button><button data-delete="${p.id}" class="link danger-text">حذف</button>`:""}<button data-report="${p.id}" class="link">إبلاغ</button></footer></article>`).join("")||`<div class="empty">لا توجد مناقشات بعد.</div>`}
async function replyPost(parentId,lectureId,courseId){const m=modal("الرد على المناقشة",`<form id="reply-form"><textarea name="content" maxlength="3000" required placeholder="اكتب ردك..."></textarea><button class="btn primary">نشر الرد</button></form>`);$("#reply-form",m).onsubmit=async e=>{e.preventDefault();try{await createPost({lectureId,courseId,parentId,content:new FormData(e.target).get("content")});m.remove();showLecture(lectureId)}catch(err){toast(err.message,"error")}}}
async function editPost(id,lectureId){const m=modal("تعديل السؤال",`<form id="edit-form"><textarea name="content" required maxlength="3000"></textarea><button class="btn primary">حفظ</button></form>`);$("#edit-form",m).onsubmit=async e=>{e.preventDefault();try{await updatePost(id,new FormData(e.target).get("content"));m.remove();showLecture(lectureId)}catch(err){toast(err.message,"error")}}}
async function startExam(examId){
 if(!auth.currentUser)return;try{const r=await fetch(APP_CONFIG.getExamQuestionsUrl,{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${await auth.currentUser.getIdToken()}`},body:JSON.stringify({examId})});const d=await r.json();if(!r.ok)throw new Error("تعذر فتح الامتحان.");const m=modal(d.exam.title,`<form id="exam-form" class="form-grid">${d.questions.map((q,i)=>`<fieldset class="card"><legend>${i+1}. ${esc(q.question)}</legend>${(q.options||[]).map((o,j)=>`<label><input type="radio" name="q_${q.id}" value="${esc(o)}" required> ${esc(o)}</label>`).join("")}</fieldset>`).join("")}<button class="btn primary">تسليم الامتحان</button></form>`);$("#exam-form",m).onsubmit=async e=>{e.preventDefault();setBusy(e.submitter,true);try{const f=new FormData(e.target),answers={};d.questions.forEach(q=>answers[q.id]=f.get(`q_${q.id}`));const r2=await fetch(APP_CONFIG.submitExamUrl,{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${await auth.currentUser.getIdToken()}`},body:JSON.stringify({examId,answers,duration:0})});const out=await r2.json();if(!r2.ok)throw new Error(out.error==="result-exists"?"تم تسجيل نتيجتك لهذا الامتحان بالفعل.":"تعذر تسليم الامتحان.");m.remove();toast(`تم التسليم: ${out.score} من ${out.total} — ${out.percentage}%`,"success")}catch(err){toast(err.message,"error")}finally{setBusy(e.submitter,false)}}}catch(e){toast(e.message,"error")}}
function bindAuth(){onAuthStateChanged(auth,async u=>{if(location.pathname.includes("/student/")&&!u&&!location.pathname.endsWith("index.html"))location.href="index.html";if(u&&location.pathname.endsWith("dashboard.html")){try{await loadDashboard()}catch(e){toast(e.message,"error")}}});}
document.addEventListener("DOMContentLoaded",()=>{bindAuth();$("#login-form")?.addEventListener("submit",async e=>{e.preventDefault();setBusy(e.submitter,true);try{await signInStudentByCode(new FormData(e.target).get("code"));location.href="dashboard.html"}catch(err){toast(err.message,"error")}finally{setBusy(e.submitter,false)}});$("#logout")?.addEventListener("click",()=>signOut(auth).then(()=>location.href="index.html"));$("#request-btn")?.addEventListener("click",()=>location.href="../index.html#register")});
